services:
  mongo:
    image: mongo:latest
    container_name: aeroroute-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aeroroute-web
    restart: always
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=DroneDeliveryDb
      - MongoDbSettings__CollectionName=DeliveryPlans
    depends_on:
      - mongo

volumes:
  mongo_data:
